public class MainObj {

    public User CreatedBy {get; set;}
    public User LModBy {get; set;}
    public String FComments {get; set;}
    public String LComments {get; set;}
    public String GComments {get; set;}
    public String ContactName {get; set;}
    public String LocName {get; set;}
    public integer Found_Main_Id {get; set;}
    public List<String> ItemType {set; get;}
    public User ownBy {get; set;}
}